### ISSUE TITLE
Build static image

### ISSUE THREAD

**Issue by fliiiix** [mikaelhg/puni2#5]
I wanted to get rid of the glibc dependency and tried to build a fully static image.
And apparently that's a thing that does not work yet and might never work for plantuml.

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported field sun.java2d.loops.DrawGlyphList.methodSignature is reachable: AWT uses fontconfig to implement font related functionality on Linux. All fontconfig uses happen through dlsym which doesn't work in a static executable. Try avoiding the use of this class in the project or turn off static executable generation.
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
	at sun.java2d.loops.DrawGlyphList.<clinit>(DrawGlyphList.java:41)
	at java.lang.Class.ensureInitialized(DynamicHub.java:525)
	at com.oracle.svm.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:348)
	at sun.java2d.loops.GraphicsPrimitiveMgr.initIDs(GraphicsPrimitiveMgr.java)
	at sun.java2d.loops.GraphicsPrimitiveMgr.<clinit>(GraphicsPrimitiveMgr.java:56)
	at sun.java2d.loops.DrawLine.locate(DrawLine.java:51)
	at sun.java2d.SurfaceData.makeRenderLoops(SurfaceData.java:884)
	at sun.awt.image.BufImgSurfaceData.getSolidLoops(BufImgSurfaceData.java:412)
	at sun.awt.image.BufImgSurfaceData.initSolidLoops(BufImgSurfaceData.java:397)
	at sun.awt.image.BufImgSurfaceData.createData(BufImgSurfaceData.java:256)
	at sun.awt.image.BufImgSurfaceData.createData(BufImgSurfaceData.java:74)
	at sun.awt.image.BufImgSurfaceManager.<init>(BufImgSurfaceManager.java:55)
	at sun.awt.image.SurfaceManager.getManager(SurfaceManager.java:79)
	at sun.java2d.SurfaceData.getPrimarySurfaceData(SurfaceData.java:275)
	at sun.java2d.SunGraphicsEnvironment.createGraphics(SunGraphicsEnvironment.java:134)
	at sun.java2d.HeadlessGraphicsEnvironment.createGraphics(HeadlessGraphicsEnvironment.java:73)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1183)
	at net.sourceforge.plantuml.FileFormat.<clinit>(FileFormat.java:128)
	at net.sourceforge.plantuml.Option.<init>(Option.java:113)
	at net.sourceforge.plantuml.Run.main(Run.java:95)
```

[0001-Build-static-image.PATCH](https://github.com/user-attachments/files/17228584/0001-Build-static-image.PATCH)

Consider this more a fyi to other people having the same idea.

**Comment by mikaelhg** [comment]
Thanks @fliiiix, we'll see if the GraalVM devs will widen the coverage of the AWT and J2D stuff.
